# Generated by Django 5.2 on 2025-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del proyecto del alumno'),
        ),
    ]
